## 1、使用numpy创建数组
**array对象的背景：**
- Numpy的核心数据结构，就叫做array就是数组，array对象可以是一维数组，也可以是多维数组；
- Python的List也可以实现相同的功能，但是array比List的优点在于性能好、包含数组元数据信息、大量的便捷函数；
- Numpy成为事实上的Scipy、Pandas、Scikit-Learn、Tensorflow、PaddlePaddle等框架的“通用底层语言”
- Numpy的array和Python的List的一个区别，是它元素必须都是同一种数据类型，比如都是数字int类型，这也是Numpy高性能的一个原因；

In [2]:
import numpy as np

In [2]:
#创建一个一维数组，也就是Python的单元素list
x = np.array([1,2,3,4,5,6,7,8,9])

In [3]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#创建一个二维数组，也就是Python的嵌套List
y = np.array([[1,2,3,4], [5,6,7,8]])

In [5]:
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## 2、探索数组array的属性

In [6]:
#shape:返回一个元组，表示array的维度，表示数组的每个维度都有多少个元素
x.shape

(9,)

In [7]:
y.shape

(2, 4)

In [8]:
#ndim:返回一个数字，表示array的维度的数目
x.ndim

1

In [9]:
y.ndim

2

In [10]:
#size:返回一个数字，表示array中所有数据元素的数目
x.size

9

In [11]:
y.size

8

In [12]:
#dtype:array中元素的数据类型
x.dtype

dtype('int32')

In [13]:
y.dtype

dtype('int32')

## 3、创建数组的便捷函数

In [15]:
#ones创建全部是1的数组，传入的是数字，就是一维数组；是元组，就是多维数组
a1 = np.ones((2,3))

In [16]:
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
#使用arange创建数字序列，arange(开始数字，结束数字，步长)
b1 = np.arange(10)

In [18]:
b1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
b2 = np.arange(2, 10, 2)

In [20]:
b2

array([2, 4, 6, 8])

In [21]:
#zeros创建一个全是0的数组，传参和ones一样
c1 = np.zeros((2,3))

In [22]:
c1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
#empty创建全是0的数组,但是这些数据都是未初始化的，可能会有随机值出现，即所有值都是无限接近于零，但是不为零
d1 = np.empty(10)

In [24]:
d1

array([6.23042070e-307, 1.89146896e-307, 1.37961302e-306, 1.05699242e-307,
       8.01097889e-307, 1.78020169e-306, 7.56601165e-307, 1.02359984e-306,
       1.33510679e-306, 2.22522597e-306])

In [25]:
#full根据指定值和指定维度创建数组，第一个参数是维度，第二个参数指定值
e1 = np.full((2,3), 666)

In [26]:
e1

array([[666, 666, 666],
       [666, 666, 666]])

In [27]:
#ones_like也是创建一个全是1的数组，但是传入的参数是一个np.array，即新创建的数组和传入数组大小一样，传数字就是一维数组
f1 = np.ones_like(y)

In [28]:
f1

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [30]:
#zeros_like也是创建一个全是0的数组，传参和ones_like一样
g1 = np.zeros_like(y)

In [31]:
g1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [32]:
#empty_like创建没有初始值的空数组（初始值为0或1，生成的数组元素都是随机数），但是未被初始化，传参同ones_like一样
h1 = np.empty_like(y)

In [33]:
h1

array([[1324770695,  805393421, 1599436526, 1645630477],
       [1745310583, 1825934317, 1801670157,  805468270]])

In [34]:
#full_like根据指定值和指定维度创建数组，第一个参数为已有数组，第二个参数指定值
i1 = np.full_like(y, 777)

In [35]:
i1

array([[777, 777, 777, 777],
       [777, 777, 777, 777]])

In [36]:
#randn()生成随机数数组,传参是一个元组，表示数组的维度
j1 = np.random.randn(2,3,4)

In [37]:
j1

array([[[ 0.61523096,  0.06627709, -0.54924483, -0.04707263],
        [ 0.26935489,  0.57059936,  0.59569932, -3.01175894],
        [ 0.23359819, -0.45406664, -0.69210378, -0.07976541]],

       [[-0.80428588,  0.81046505, -0.85215091, -0.67863212],
        [ 0.36932609, -0.33384821, -0.2946785 , -1.11207655],
        [ 0.65956243,  0.32450136,  1.07656175, -1.81201496]]])

In [38]:
#reshape把指定矩阵转换为特定矩阵,后面的参数是矩阵的维度的具体参数
k1 = y.reshape(4,2)

In [39]:
k1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [3]:
#numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
#在指定的间隔内返回均匀间隔的数字，可以包括start和stop，num表示样本数
#endpoint : bool,如果是真，则一定包括stop，如果为False，一定不会有stop（默认为true）
k2 = np.linspace(-5,5,50)

In [4]:
k2

array([-5.        , -4.79591837, -4.59183673, -4.3877551 , -4.18367347,
       -3.97959184, -3.7755102 , -3.57142857, -3.36734694, -3.16326531,
       -2.95918367, -2.75510204, -2.55102041, -2.34693878, -2.14285714,
       -1.93877551, -1.73469388, -1.53061224, -1.32653061, -1.12244898,
       -0.91836735, -0.71428571, -0.51020408, -0.30612245, -0.10204082,
        0.10204082,  0.30612245,  0.51020408,  0.71428571,  0.91836735,
        1.12244898,  1.32653061,  1.53061224,  1.73469388,  1.93877551,
        2.14285714,  2.34693878,  2.55102041,  2.75510204,  2.95918367,
        3.16326531,  3.36734694,  3.57142857,  3.7755102 ,  3.97959184,
        4.18367347,  4.3877551 ,  4.59183673,  4.79591837,  5.        ])

## 4、对numpy数组的基本运算

In [40]:
l1 = np.arange(2, 10, 2)

In [41]:
l1

array([2, 4, 6, 8])

In [42]:
l1 + 1

array([3, 5, 7, 9])

In [47]:
l1 - 1

array([1, 3, 5, 7])

In [46]:
l1 * 2

array([ 4,  8, 12, 16])

In [48]:
l1 / 2

array([1., 2., 3., 4.])

In [49]:
l1 ** 2

array([ 4, 16, 36, 64], dtype=int32)

In [50]:
#对于形状相同的数组，它们对位的元素可以相互之间相加相减相乘
m1 = np.arange(2,10,2)
m2 = np.arange(10,18,2)

In [51]:
m1

array([2, 4, 6, 8])

In [52]:
m2

array([10, 12, 14, 16])

In [53]:
m1 + m2

array([12, 16, 20, 24])

In [54]:
m1 - m2

array([-8, -8, -8, -8])

In [55]:
m1 * m2

array([ 20,  48,  84, 128])

In [56]:
#对于一个数组，可以使用一些运算符对每个元素进行运算
n1 = np.arange(2,10,2)

In [57]:
np.sin(n1)

array([ 0.90929743, -0.7568025 , -0.2794155 ,  0.98935825])

In [58]:
np.cos(n1)

array([-0.41614684, -0.65364362,  0.96017029, -0.14550003])

In [59]:
np.exp(n1)

array([   7.3890561 ,   54.59815003,  403.42879349, 2980.95798704])