## 5、numpy常用random随机函数汇总

In [3]:
import numpy as np

In [4]:
#设置随机数种子,这样每次的随机数都会是一样的
np.random.seed(7788)

In [5]:
#rand()返回数据在[0,1]之间，具有均匀分布，填入的数据是返回数据的维度
#如果所传的维度是已有的数组，则用*a.shape
a1 = np.random.rand(5)

In [6]:
a1

array([0.2588578 , 0.89372399, 0.14532874, 0.57924809, 0.07949612])

In [7]:
a2 = np.random.rand(3, 4)

In [8]:
a2

array([[0.67089029, 0.56992917, 0.12867291, 0.20889038],
       [0.48045338, 0.30385425, 0.91545276, 0.15289611],
       [0.23009923, 0.69333139, 0.33883606, 0.02324716]])

In [9]:
a3 = np.random.rand(2,3,4)

In [10]:
a3

array([[[0.18995642, 0.63727857, 0.5854967 , 0.51362067],
        [0.72712617, 0.00176792, 0.44513589, 0.10005319],
        [0.76673351, 0.14898728, 0.3955206 , 0.18176142]],

       [[0.00934895, 0.18555107, 0.29242548, 0.8312476 ],
        [0.93236516, 0.31266739, 0.78835571, 0.15255151],
        [0.70893855, 0.92486654, 0.20543847, 0.57679846]]])

In [11]:
#randn()返回数据具有正态分布（均值为0，方差为1）
b1 = np.random.randn(5)

In [12]:
b1

array([-0.84745549,  0.52680109, -0.25265528,  1.19901865, -0.34907687])

In [13]:
b2 = np.random.randn(3,4)

In [14]:
b2

array([[-1.13126028, -0.29843541,  0.05057141,  0.19810505],
       [-0.77570776,  0.72615516, -1.4050286 ,  0.62508468],
       [ 0.92975448,  1.13666265,  0.0417938 ,  0.00143252]])

In [15]:
#randint(low,high,size())随机生成整数，包含low，不包含high，size是维度
c1 = np.random.randint(10, 20, size=(5,4))

In [16]:
c1

array([[11, 15, 14, 11],
       [17, 14, 15, 17],
       [17, 13, 10, 19],
       [11, 15, 15, 11],
       [18, 19, 15, 14]])

In [17]:
#随机一个从0到1999的数字
c2 = np.random.randint(1999)

In [18]:
c2

429

In [19]:
#随机一个从9到1999的数字
c3 = np.random.randint(9, 1999)

In [20]:
c3

546

In [21]:
#random(size = )生成0.0到1.0之间的随机数，传入的是随机数的维度
d1 = np.random.random(size = (1,4))

In [22]:
d1

array([[0.15740738, 0.86226132, 0.70521203, 0.45352676]])

In [23]:
#choice(数组或数字， 维度)从数组中取出相应维度大小的数字
#如果前面是数字，则从0到这个数字来取值
e1 = np.random.choice(5, (2,3))

In [24]:
e1

array([[3, 2, 3],
       [3, 1, 2]])

In [25]:
e2 = np.random.choice((1111, 1132112312), (2, 3))

In [26]:
e2

array([[      1111, 1132112312,       1111],
       [1132112312, 1132112312,       1111]])

In [27]:
#uniform(最小值，最大值，维度),在low和high之间生成均匀分布的数字
f1 = np.random.uniform(1,10,(5,5))

In [28]:
f1

array([[3.43677919, 3.91417715, 9.95215631, 9.52090642, 2.25322534],
       [9.47661206, 1.15781777, 3.5432489 , 4.20504527, 5.20678677],
       [3.77132775, 2.87752415, 7.82116668, 4.02448221, 3.17759403],
       [4.65954111, 9.01747573, 5.36348908, 9.65208603, 1.28586719],
       [2.21010936, 4.2259005 , 2.05406147, 7.78139433, 5.48047021]])

In [29]:
#normal(均值，方差，维度)，根据平均值和方差生成高斯分布的数字
g1 = np.random.normal(1,10,(3,5))

In [30]:
g1

array([[-10.30348391,  -8.35012443,   5.49222643,   0.78610439,
          6.20226166],
       [  2.29080006,  -2.73146705,   2.1273423 , -12.37280901,
          5.89760121],
       [  6.10814171,  14.27835916,  18.0905348 , -13.88934705,
         16.51654751]])

In [32]:
#permutation()把一个数组x进行随机排列，或者数字的全排列
#从0-10挑选10个数，进行随机排列
h1 = np.random.permutation(10)

In [33]:
h1

array([5, 4, 8, 9, 0, 3, 2, 7, 1, 6])

In [34]:
h2 = np.arange(9).reshape((3,3))
h3 = np.random.permutation(h2)#对多维数组进行全排列，所以不会改变原数组

In [35]:
h3

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [47]:
#shuffle()对一维数组进行随机排列，如果是多维数组，那么只会在第一个维度上打乱数字，即打乱每一行，但其中每一行的数字的排序不变
i2 = np.arange(10)
i2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.random.shuffle(i2)#操作是对原数组进行操作的，所以就没有返回值
i2

array([0, 5, 1, 6, 3, 7, 8, 4, 9, 2])

In [49]:
i3 = np.arange(30).reshape(5,6)
i3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [50]:
np.random.shuffle(i3)
i3

array([[12, 13, 14, 15, 16, 17],
       [24, 25, 26, 27, 28, 29],
       [ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23],
       [ 0,  1,  2,  3,  4,  5]])