## 10、数组的排序
3个方法都支持一个参数kind，可以是以下一个值：

- quicksort：快速排序，平均O(nlogn)，不稳定情况
- mergesort：归并排序，平均O(nlogn)，稳定排序
- heapsort：堆排序，平均O(nlogn)，不稳定排序
- stable：稳定排序
- kind默认值是quicksort，快速排序平均情况是最快，保持默认即可

numpy的排序速度比原生python的排序要快

In [4]:
import numpy as np

In [13]:
a1 = np.random.randint(10, 100, size = (10))

In [14]:
a1

array([85, 51, 52, 70, 47, 87, 25, 13, 67, 73])

In [15]:
#返回一个新的从小到大的数组
np.sort(a1)

array([13, 25, 47, 51, 52, 67, 70, 73, 85, 87])

In [16]:
#返回的是排序后的数组中的数字在排序好的数组中的（新）位置
np.argsort(a1)

array([7, 6, 4, 1, 2, 8, 3, 9, 0, 5], dtype=int64)

In [17]:
#结合条件索引和返回数组的位置，获取排序数组
a1[np.argsort(a1)]

array([13, 25, 47, 51, 52, 67, 70, 73, 85, 87])

In [18]:
#对数组进行原地排序
a1.sort()

## 11、数组的乘法

numpy有以下乘法函数：

- *符号或者np.multiply：逐元素乘法，对应位置的元素相乘，要求shape相同
- @符号或者np.matmul：矩阵乘法，形状要求满足(n,k),(k,m)->(n,m)
- np.dot：点积乘法

In [5]:
#数字和一维数组相乘
#这里可以换为其他的多维数组
b1 = np.arange(12).reshape(3,4)

In [6]:
b1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
b1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [22]:
#一维数组和一维数组相乘，需要长度相同，并且是注意元素相乘
b2 = np.arange(10)
b3 = np.random.randint(10, 20, size = (10))

In [23]:
b2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
b3

array([11, 19, 13, 13, 14, 11, 15, 14, 16, 17])

In [25]:
#与np.multiply(b2, b3)效果一样
b2 * b3

array([  0,  19,  26,  39,  56,  55,  90,  98, 128, 153])

In [32]:
#二维数组乘一维数组，注意一维数组的个数要和二维数组的列相同,也是注意元素相乘
b4 = np.random.randint(10, 20, size = (5))
b5 = np.arange(10).reshape(2,5)

In [33]:
b4

array([12, 11, 10, 16, 10])

In [34]:
b5

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [35]:
#np.multiply(b4, b5)
#以上效果相同
b4 * b5

array([[  0,  11,  20,  48,  40],
       [ 60,  66,  70, 128,  90]])

## 12、数组的点积与矩阵的乘法
两个向量a = [a1, a2,…, an]和b = [b1, b2,…, bn]的点积定义为：
a·b=a1b1+a2b2+……+anbn。

In [26]:
#先创建两个数组
#copy是复制一个和原来一模一样的数组
c1 = np.arange(12)
c2 = c1.copy()

In [27]:
#数组的点积
#np.matmul(c1, c2)
#np.dot(c1, c2)
#np.sum(a1 * a2)
#以上的效果都是等价的
c1@c2

506

In [28]:
#由点积可以推出矩阵的乘法
d1 = np.random.randint(10, 20 ,size = (3, 4))
d2 = np.random.randint(10, 20 ,size = (4, 3))

In [29]:
d1

array([[16, 19, 14, 11],
       [13, 17, 15, 19],
       [19, 17, 15, 14]])

In [30]:
d2

array([[10, 18, 12],
       [19, 17, 18],
       [13, 18, 17],
       [17, 15, 18]])

In [31]:
#计算矩阵的乘法
#np.matmul(d1, d2)
#np.dot(d1, d2)
#以上的效果都相同
d1@d2

array([[ 890, 1028,  970],
       [ 971, 1078, 1059],
       [ 946, 1111, 1041]])

## 13、广播的概念
如果两个数组的维度数dim不相同，那么小维度数组的形状将会在 左边 补1

如果shape的维度不匹配，但是有维度是1，那么可以扩展维度是1的维度匹配另一个数组；

如果shape的维度不匹配，但是没有任何一个维度是1，则匹配失败引发错误；

适用于数组之间的加减乘除

即只要有相同的维度上有相同的数，便可以广播拓展运算

In [36]:
#先创建两个数组
f1 = np.random.randint(10, 20, size = (3,4))
f2 = np.arange(4)

In [38]:
f1

array([[17, 10, 13, 16],
       [12, 17, 12, 13],
       [18, 17, 14, 19]])

In [39]:
f2

array([0, 1, 2, 3])

In [37]:
#分析：f2是一个一维数组有四个位置，首先在其左边添加一个维度，变为（1，4）然后把为1的位置拓展至另外一个数组匹配，即变为（3，4），便可以相加了
f1 + f2

array([[17, 11, 15, 19],
       [12, 18, 14, 16],
       [18, 18, 16, 22]])

In [40]:
#再创建两个数组
g1 = np.arange(3).reshape((3,1))
g2 = np.arange(3)

In [41]:
g1

array([[0],
       [1],
       [2]])

In [42]:
g2

array([0, 1, 2])

In [43]:
#分析：分析：根据规则1，g2.shape会变成(1, 3)
#根据规则2，g2.shape再变成(3, 3)，相当于在行上复制
#根据规则2，g1.shape再变成(3, 3)，相当于在列上复制
g1 + g2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])